### ISSUE TITLE
Descriptive errors for invalid logins

### ISSUE THREAD

**Issue by harry-lons** [harry-lons/SoCalSocial#6]
Users should be provided with the following feedback when incorrectly logging in:

[ Account does not exist ] : Users should be given an error that this email is not registered with our site, and we should suggest that they check they typed the correct email address, or sign up if they haven't

[ Incorrect password ] : Users should be told that they have entered an incorrect password.

[ Invalid inputs ] : Users should be told they have entered an invalid email, too long of a password, or missing an input

**Comment by AZA-2003** [comment]
Estimated time: 2 hours

**Comment by harry-lons** [comment]
#147
